---
name: "OMDb Enhanced"
guid: "09b5086a-e404-420d-b661-2bc24143eaaa"
version: 1
targetAbi: "10.10.0.0"
framework: "net8.0"
owner: "bakeneko"
overview: "Get OMDb metadata"
description: >
  Get metadata for movies and other video content from OMDb.
category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.OMDbEnhanced.dll"
changelog: |-
  - First release @bakeneko
