---
name: "OMDb Enhanced"
guid: "09b5086a-e404-420d-b661-2bc24143eaaa"
version: 2
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "bakeneko"
overview: "Get OMDb metadata"
description: >
  Get metadata for movies and other video content from OMDb.

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.OMDbEnhanced.dll"
changelog: |-
  - Update for Jellyfin 10.11.0
