name: "🆙 Bump Version"

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/bump-version.yaml@master
    with:
      default-branch: main
      csproj-name: Jellyfin.Plugin.OMDbEnhanced
      is-unstable: ${{ github.event.release.prerelease }}
      commiter-name: GitHub Actions
      commiter-email: actions@github.com