name: '🚀 Publish Plugin'

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: main

      - name: Setup .NET
        uses: actions/setup-dotnet@87b7050bc53ea08284295505d98d2aa94301e852 # v4.2.0
        with:
          dotnet-version: 9.0.x
          
      - name: Setup jprm
        run: |
          pip install --user jprm

      - name: Build Jellyfin Plugin
        uses: oddstr13/jellyfin-plugin-repository-manager@9497a0a499416cc572ed2e07a391d9f943a37b4d # v1.1.1
        id: jprm
        with:
          dotnet-target: net9.0
          output: ./artifacts

      - name: Prepare GH Release Assets
        run: |-
          mkdir ./upload
          cp ${{ steps.jprm.outputs.artifact }} ./upload
          for file in ./upload/*; do
            md5sum ${file#./} >> ${file%.*}.md5
            sha256sum ${file#./} >> ${file%.*}.sha256
          done
          ls -l

      - name: Upload GH Release Assets
        id: release
        uses: shogo82148/actions-upload-release-asset@8482bd769644976d847e96fb4b9354228885e7b4 # v1.7.8
        with:
          upload_url: ${{ github.event.release.upload_url }}
          overwrite: true
          asset_path: ./upload/*

      - name: Update manifest
        run: |
          jprm repo add --plugin-url $(echo "${{ steps.release.outputs.browser_download_url }}" | sed -n 3p) ./manifest.json ./upload/*.zip

      - name: Commit manifest
        run: |
          git config user.name GitHub Actions
          git config user.email actions@github.com
          git pull
          git add ./manifest.json
          git commit -m "Update manifest.json"
          git push --force origin main
      
